/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const House = IDL.Record({
  'id' : IDL.Text,
  'downPayment' : IDL.Float64,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'totalCost' : IDL.Float64,
  'interestRate' : IDL.Float64,
  'loanTermYears' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DashboardSummary = IDL.Record({
  'totalInterest' : IDL.Float64,
  'totalCost' : IDL.Float64,
  'totalPayments' : IDL.Nat,
  'totalPaid' : IDL.Float64,
  'overallProgress' : IDL.Float64,
  'totalHouses' : IDL.Nat,
  'remainingBalance' : IDL.Float64,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const HouseWithProgress = IDL.Record({
  'house' : House,
  'progressPercentage' : IDL.Float64,
  'totalAmountToPay' : IDL.Float64,
  'totalPaid' : IDL.Float64,
  'remainingBalance' : IDL.Float64,
  'interestAmount' : IDL.Float64,
});
export const OverviewData = IDL.Record({
  'dashboardSummary' : DashboardSummary,
  'userProfile' : UserProfile,
  'housesWithProgress' : IDL.Vec(HouseWithProgress),
});
export const AppVersion = IDL.Record({
  'major' : IDL.Nat,
  'minor' : IDL.Nat,
  'build' : IDL.Nat,
  'patch' : IDL.Nat,
});
export const HouseProgress = IDL.Record({
  'downPayment' : IDL.Float64,
  'progressPercentage' : IDL.Float64,
  'totalPaid' : IDL.Float64,
  'remainingBalance' : IDL.Float64,
  'loanTermYears' : IDL.Nat,
  'interestAmount' : IDL.Float64,
  'totalLoanAmount' : IDL.Float64,
});
export const Payment = IDL.Record({
  'paymentMethod' : IDL.Text,
  'date' : IDL.Int,
  'note' : IDL.Text,
  'amount' : IDL.Float64,
  'houseId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addOrUpdateHouse' : IDL.Func([House], [], []),
  'addPayment' : IDL.Func(
      [IDL.Float64, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Int)],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteHouse' : IDL.Func([IDL.Text], [], []),
  'deletePayment' : IDL.Func([IDL.Nat], [], []),
  'editPayment' : IDL.Func(
      [IDL.Nat, IDL.Float64, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
      [],
      [],
    ),
  'getAllHouses' : IDL.Func([], [IDL.Vec(House)], ['query']),
  'getBootstrapData' : IDL.Func([], [OverviewData], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentAppVersion' : IDL.Func([], [AppVersion], ['query']),
  'getHouse' : IDL.Func([IDL.Text], [IDL.Opt(House)], ['query']),
  'getHouseProgress' : IDL.Func([IDL.Text], [HouseProgress], ['query']),
  'getInitializationStatus' : IDL.Func([], [IDL.Text], ['query']),
  'getPaymentHistoryByHouse' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Payment)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'healthCheck' : IDL.Func([], [IDL.Text], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isUpdateAvailable' : IDL.Func([AppVersion], [IDL.Bool], ['query']),
  'safeInitialize' : IDL.Func([], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const House = IDL.Record({
    'id' : IDL.Text,
    'downPayment' : IDL.Float64,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'totalCost' : IDL.Float64,
    'interestRate' : IDL.Float64,
    'loanTermYears' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DashboardSummary = IDL.Record({
    'totalInterest' : IDL.Float64,
    'totalCost' : IDL.Float64,
    'totalPayments' : IDL.Nat,
    'totalPaid' : IDL.Float64,
    'overallProgress' : IDL.Float64,
    'totalHouses' : IDL.Nat,
    'remainingBalance' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const HouseWithProgress = IDL.Record({
    'house' : House,
    'progressPercentage' : IDL.Float64,
    'totalAmountToPay' : IDL.Float64,
    'totalPaid' : IDL.Float64,
    'remainingBalance' : IDL.Float64,
    'interestAmount' : IDL.Float64,
  });
  const OverviewData = IDL.Record({
    'dashboardSummary' : DashboardSummary,
    'userProfile' : UserProfile,
    'housesWithProgress' : IDL.Vec(HouseWithProgress),
  });
  const AppVersion = IDL.Record({
    'major' : IDL.Nat,
    'minor' : IDL.Nat,
    'build' : IDL.Nat,
    'patch' : IDL.Nat,
  });
  const HouseProgress = IDL.Record({
    'downPayment' : IDL.Float64,
    'progressPercentage' : IDL.Float64,
    'totalPaid' : IDL.Float64,
    'remainingBalance' : IDL.Float64,
    'loanTermYears' : IDL.Nat,
    'interestAmount' : IDL.Float64,
    'totalLoanAmount' : IDL.Float64,
  });
  const Payment = IDL.Record({
    'paymentMethod' : IDL.Text,
    'date' : IDL.Int,
    'note' : IDL.Text,
    'amount' : IDL.Float64,
    'houseId' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addOrUpdateHouse' : IDL.Func([House], [], []),
    'addPayment' : IDL.Func(
        [IDL.Float64, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Int)],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteHouse' : IDL.Func([IDL.Text], [], []),
    'deletePayment' : IDL.Func([IDL.Nat], [], []),
    'editPayment' : IDL.Func(
        [IDL.Nat, IDL.Float64, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
        [],
        [],
      ),
    'getAllHouses' : IDL.Func([], [IDL.Vec(House)], ['query']),
    'getBootstrapData' : IDL.Func([], [OverviewData], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentAppVersion' : IDL.Func([], [AppVersion], ['query']),
    'getHouse' : IDL.Func([IDL.Text], [IDL.Opt(House)], ['query']),
    'getHouseProgress' : IDL.Func([IDL.Text], [HouseProgress], ['query']),
    'getInitializationStatus' : IDL.Func([], [IDL.Text], ['query']),
    'getPaymentHistoryByHouse' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Payment)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'healthCheck' : IDL.Func([], [IDL.Text], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isUpdateAvailable' : IDL.Func([AppVersion], [IDL.Bool], ['query']),
    'safeInitialize' : IDL.Func([], [IDL.Text], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };