/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppVersion {
  'major' : bigint,
  'minor' : bigint,
  'build' : bigint,
  'patch' : bigint,
}
export interface DashboardSummary {
  'totalInterest' : number,
  'totalCost' : number,
  'totalPayments' : bigint,
  'totalPaid' : number,
  'overallProgress' : number,
  'totalHouses' : bigint,
  'remainingBalance' : number,
}
export interface House {
  'id' : string,
  'downPayment' : number,
  'name' : string,
  'createdAt' : bigint,
  'totalCost' : number,
  'interestRate' : number,
  'loanTermYears' : bigint,
}
export interface HouseProgress {
  'downPayment' : number,
  'progressPercentage' : number,
  'totalPaid' : number,
  'remainingBalance' : number,
  'loanTermYears' : bigint,
  'interestAmount' : number,
  'totalLoanAmount' : number,
}
export interface HouseWithProgress {
  'house' : House,
  'progressPercentage' : number,
  'totalAmountToPay' : number,
  'totalPaid' : number,
  'remainingBalance' : number,
  'interestAmount' : number,
}
export interface OverviewData {
  'dashboardSummary' : DashboardSummary,
  'userProfile' : UserProfile,
  'housesWithProgress' : Array<HouseWithProgress>,
}
export interface Payment {
  'paymentMethod' : string,
  'date' : bigint,
  'note' : string,
  'amount' : number,
  'houseId' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addOrUpdateHouse' : ActorMethod<[House], undefined>,
  'addPayment' : ActorMethod<
    [number, string, string, string, [] | [bigint]],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteHouse' : ActorMethod<[string], undefined>,
  'deletePayment' : ActorMethod<[bigint], undefined>,
  'editPayment' : ActorMethod<
    [bigint, number, string, string, string, bigint],
    undefined
  >,
  'getAllHouses' : ActorMethod<[], Array<House>>,
  'getBootstrapData' : ActorMethod<[], OverviewData>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentAppVersion' : ActorMethod<[], AppVersion>,
  'getHouse' : ActorMethod<[string], [] | [House]>,
  'getHouseProgress' : ActorMethod<[string], HouseProgress>,
  'getInitializationStatus' : ActorMethod<[], string>,
  'getPaymentHistoryByHouse' : ActorMethod<[string], Array<Payment>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'healthCheck' : ActorMethod<[], string>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isUpdateAvailable' : ActorMethod<[AppVersion], boolean>,
  'safeInitialize' : ActorMethod<[], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];